CREATE TABLE IDENTITIES
	(IDENTITIES_ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY 
	(START WITH 1, INCREMENT BY 1), 
	IDENTITIES_FIRSTNAME VARCHAR(100), 
	IDENTITIES_LASTNAME VARCHAR(100),
	IDENTITIES_EMAIL VARCHAR(255),
	IDENTITIES_BIRTHDATE DATE
	);